name: Tests
on:
  push:
    branches: [ gh-actions-testing ]
  pull_request:
    branches: [ gh-actions-testing ]
jobs:
  Explore-GitHub-Actions:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run install-all
      - run: npm run test
      - run: npm run lint
